teams:
  - name: lf-staff
    maintainers:
      - jwagantall
      - ryjones
    members: []
  - name: pdp-connect-maintainers
    maintainers:
      - tnunamak
    members:
      - annakaz
      - artvana
      - volod-vana
      - letonchanh
      - maciejwitowski
      - Kahtaf
repositories:
  - name: .github
    teams:
      lf-staff: maintain
      pdp-connect-maintainers: maintain
    visibility: public
  - name: governance
    teams:
      lf-staff: maintain
      pdp-connect-maintainers: maintain
    visibility: public
  - name: pdpp
    teams:
      lf-staff: maintain
      pdp-connect-maintainers: maintain
    visibility: public
  - name: data-connect
    teams:
      lf-staff: maintain
      pdp-connect-maintainers: maintain
    visibility: public
  - name: data-connectors
    teams:
      lf-staff: maintain
      pdp-connect-maintainers: maintain
    visibility: public
